#!/usr/bin/env ruby

require 'sitemap_generator'

SitemapGenerator::Sitemap.default_host = 'https://word2md.com'
SitemapGenerator::Sitemap.verbose = true
SitemapGenerator::Sitemap.compress = false

SitemapGenerator::Sitemap.create do
  add '/privacy'
  add '/terms'
end

SitemapGenerator::Sitemap.ping_search_engines
