name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Install Libreoffice
      run: | 
        sudo add-apt-repository ppa:libreoffice/ppa
        sudo apt-get install -y --no-install-recommends libreoffice-writer
    - name: Run tests
      run: script/cibuild