# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - word2md

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_30ea4d9721c4436bb588d565bee5017f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8d3453ca84b74a5da6ae4825bbdbf3ec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_30ea4d9721c4436bb588d565bee5017f }}/benbalter/word-to-markdown-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'word2md'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_552870e2db4547f7bdb39c5280470ab3 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_30ea4d9721c4436bb588d565bee5017f }}/benbalter/word-to-markdown-server:${{ github.sha }}'